# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# for vim-jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# React JSX
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript.jsx'

# Coq syntax
[[plugins]]
repo = 'jvoorhis/coq.vim'
on_ft = 'coq'

# Scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'wlangstroth/vim-racket'
on_ft = 'racket'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
  let g:quickrun_config = {
              \   "_" : {
              \       "runner" : "vimproc",
              \       "runner/vimproc/updatetime" : 60
              \   },
              \   "c": {
              \      "cmdopt" : "-std=c99"
              \   }
              \}
'''

[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = 'Ref'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'
hook_source = 'source ~/.vim/config/plugins/latex.vim'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = [['nx', '<Plug>']]
hook_add = '''
  nmap <Leader>c <Plug>(caw:hatpos:toggle)
  vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''
