[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make' # Linux & OS X only

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  "let g:molokai_original = 1
  let g:rehash256 = 1
  set background=dark
  " カーソル行の背景色を変える
  set cursorline
  colorscheme molokai
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'editorconfig/editorconfig-vim'
