# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# for vim-jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# React JSX
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript.jsx'

# Coq syntax
[[plugins]]
repo = 'jvoorhis/coq.vim'
on_ft = 'coq'

# Scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
